services:
  frontend:
    build: ./frontend
    image: ${IMAGE_REGISTRY:-registry.humanitec.io/public}/bank-demo-frontend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONEY_API_URL=http://moneyapi:3000/trpc
      - USERS_API_URL=http://usersapi:3000/trpc
    depends_on:
      - moneyapi
      - usersapi

  moneyapi:
    build: ./money-api
    image: ${IMAGE_REGISTRY:-registry.humanitec.io/public}/bank-demo-money-api
    environment:
      - PORT=3000
      - DB_DATABASE=bank
      - DB_USER=bank
      - DB_PASSWORD=secret
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy

  usersapi:
    build: ./users-api
    image: ${IMAGE_REGISTRY:-registry.humanitec.io/public}/bank-demo-users-api
    environment:
      - PORT=3000

  report-worker:
    build: ./report-worker
    image: ${IMAGE_REGISTRY:-registry.humanitec.io/public}/bank-demo-report-worker

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=bank
      - MYSQL_USER=bank
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
