name: Build Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      image-name:
        required: true
        type: string
      HUMANITEC_ORG:
        required: true
        type: string
    secrets:
      HUMANITEC_TOKEN:
        required: true
    outputs:
      IMAGE_NAME: 
        description: "The name of the image that was built"
        value: ${{ jobs.build-service.outputs.IMAGE_NAME }}
      IMAGE_TAG: 
        description: "The tag of the image that was built"
        value: ${{ jobs.build-service.outputs.IMAGE_TAG }}

jobs:

  build-service:

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ inputs.image-name }}

    outputs:
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      IMAGE_TAG: ${{ steps.settag.outputs.IMAGE_TAG }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: yarn
      working-directory: ./${{ inputs.service-name }}

    - name: Build Code
      run: yarn run build
      working-directory: ./${{ inputs.service-name }}
    
    - name: Set Tag
      run: |
        IMAGE_TAG=$(date "+%Y-%m-%d_%H-%M-%S")
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
      id: settag

    - name: Build docker image
      run: docker build . --tag ${IMAGE_NAME}:${IMAGE_TAG}
      working-directory: ./${{ inputs.service-name }}

    - uses: humanitec/build-push-to-humanitec@v1
      name: Build and push the Docker image with humanitec plugin
      with:
        humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
        organization: ${{ inputs.HUMANITEC_ORG }}
        existing-image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
    
    - name: Tag Latest
      run: docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest

    - uses: humanitec/build-push-to-humanitec@v1
      name: Build and push the Docker image with humanitec plugin
      with:
        humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
        organization: ${{ inputs.HUMANITEC_ORG }}
        existing-image: ${{ env.IMAGE_NAME }}:latest